parallel-jobs = 1
enable-module-update = false
dpi = "nodpi 120-640dpi"

[Tiktok]
enabled = true
app-name = "Tiktok"
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
build-mode = "apk"
version = "43.6.2"
included-patches = "'Settings'"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=com.morphe.zhiliaoapp.musically"

[Instagram]
enabled = false
app-name = "Instagram"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
reset-prebuilts = true
rv-brand = "Piko"
uptodown-dlurl = "https://instagram.en.uptodown.com/android/"
# direct-dlurl = "https://github.com/shipwr3ckd/apks/releases/download/Release/com.instagram.android_423.0.0.47.66.apk"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change version code' -OversionCode=2147483647"

[Twitter]
enabled = false
app-name = "X"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
reset-prebuilts = true
rv-brand = "Piko"
uptodown-dlurl = "https://twitter.en.uptodown.com/android/"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
build-mode = "apk"
version = "11.67.0-release.0"
arch = "arm64-v8a"
included-patches = "'Add ability to copy media link' 'Clear tracking params' 'Control video auto scroll' 'Custom download folder' 'Custom emoji font' 'Custom font' 'Custom sharing domain' 'Custom translator' 'Customise post font size' 'Customize Inline action Bar items' 'Customize Navigation Bar items' 'Customize default reply sorting' 'Customize explore tabs' 'Customize notification tabs' 'Customize profile tabs' 'Customize search suggestions' 'Customize search tab items' 'Customize side bar items' 'Customize timeline top bar' 'Disable auto timeline scroll on launch' 'Disable chirp font' 'Disunify xchat system' 'Download patch' 'Dynamic color' 'Enable Undo Posts' 'Enable force HD videos' 'Force enable translate' 'Handle custom twitter links' 'Hide Banner' 'Hide FAB' 'Hide FAB Menu Buttons' 'Hide Live Threads' 'Hide Recommended Users' 'Hide badges from navigation bar icons' 'Hide bookmark icon in timeline' 'Hide hidden replies' 'Hide immersive player' 'Hide nudge button' 'Hide promote button' 'Hide timeline posts by category' 'Hook feature flag' 'Native reader mode' 'No shortened URL' 'Remove Ads' 'Remove premium upsell' 'Remove view count' 'Round off numbers' 'Selectable Text' 'Share Tweet as Image' 'Show poll results' 'Show post source label'"
patcher-args = "-e 'Change app icon' -OappIcon=original -e 'Change version code' -OversionCode=2147483647"

[Letterboxd]
enabled = false
app-name = "Letterboxd"
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
reset-prebuilts = true
rv-brand = "De-ReVanced"
uptodown-dlurl = "https://letterboxd.en.uptodown.com/android/"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/letterboxd-limited/letterboxd/"
build-mode = "apk"
version = "latest"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Unlock app icons'"
patcher-args = "-e 'Change package name' -OpackageName=com.morphe.letterboxd.letterboxd"

[Google-Photos]
enabled = false
app-name = "Google Photos"
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
reset-prebuilts = true
rv-brand = "De-ReVanced"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android/"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=app.morphe.android.photos"

[ProtonMail]
enabled = false
app-name = "Proton Mail"
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
reset-prebuilts = true
rv-brand = "De-ReVanced"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android/"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email/"
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=ch.morphe.protonmail.android"

[YouTube]
enabled = false
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
reset-prebuilts = true
rv-brand = "Morphe"
uptodown-dlurl = "https://youtube.en.uptodown.com/android/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
included-patches = "'Alternative thumbnails' 'Ambient mode' 'Bypass URL redirects' 'Bypass image region restrictions' 'Captions' 'Change start page' 'Check watch history domain name resolution' 'Copy video URL' 'Custom branding' 'Custom player overlay opacity' 'Disable DRC audio' 'Disable QUIC protocol' 'Disable double tap actions' 'Disable haptic feedback' 'Disable layout updates' 'Disable player popup panels' 'Disable resuming Shorts on startup' 'Disable sign in to TV popup' 'Disable video codecs' 'Double tap to seek' 'Downloads' 'Enable debugging' 'Exit fullscreen mode' 'Force original audio' 'GmsCore support' 'Hide Shorts components' 'Hide ads' 'Hide autoplay preview' 'Hide end screen cards' 'Hide end screen suggested video' 'Hide info cards' 'Hide layout components' 'Hide player flyout menu items' 'Hide player overlay buttons' 'Hide related video overlay' 'Hide timestamp' 'Hide video action buttons' 'Loop video' 'Miniplayer' 'Navigation bar' 'Open links externally' 'Open videos fullscreen' 'Playback speed' 'Remove background playback restrictions' 'Remove viewer discretion dialog' 'Return YouTube Dislike' 'Sanitize sharing links' 'Seekbar' 'SponsorBlock' 'Spoof app version' 'Spoof device dimensions' 'Swipe controls' 'Theme' 'Video ads' 'Video quality'"
patcher-args = "-e 'Change package name' -OpackageName=app.revanced.android.youtube -e 'Change version code' -OversionCode=2147483647"
